apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuber
  template:
    metadata:
      labels:
        app: kuber
    spec:
      containers:
        - name: kuber
          image: valomia18/kuber.io:1.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  selector:
    app: kuber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort